const homeData = [
    {
        streetAddress: "55 Bergen St",
        city: "Brooklyn",
        state: "New York",
        bedrooms: "2",
        bathrooms: "2",
        price: "$123456",
    },
    {
        streetAddress: "208 Flatbush Ave",
        city: "Brooklyn",
        state: "New York",
        bedrooms: "2",
        bathrooms: "1",
        price: "$123456",
    },
    {
        streetAddress: "124 N. 6th St",
        city: "Brooklyn",
        state: "New York",
        bedrooms: "1",
        bathrooms: "2",
        price: "$123456",
    },
    {
        streetAddress: "424 Columbus Ave",
        city: "New York",
        state: "New York",
        bedrooms: "1",
        bathrooms: "1",
        price: "$123456",
    },
    {
        streetAddress: "121 Greene St",
        city: "New York",
        state: "New York",
        bedrooms: "1",
        bathrooms: "1",
        price: "$123456",
    },
    {
        streetAddress: "1209 Lexington Ave",
        city: "New York",
        state: "New York",
        bedrooms: "studio",
        bathrooms: "1",
        price: "$123456",
    },
];